export enum ResponseCode {
  VERIFY_ACCOUNT = 'VERIFY_ACCOUNT',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  OTP_SENT = 'OTP_SENT',
  OTP_IS_VALID = 'OTP_IS_VALID',
  CREATE_PIN = 'CREATE_PIN',
  LOGGED_IN = 'LOGGED_IN',
  OK = 'OK',
  NOT_FOUND = 'NOT_FOUND',
}
